name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"

      - name: Install NPM packages
        run: npm install

      - name: Build Landing page (svelte) application
        run: npm run build

      - name: Prepare static presentations
        run: npm run slides:init

      - name: Copy static presentations
        run: npm run slides:copy-static

      - name: Generate "Carbon now" images from snippets
        run: npm run generate:code-images

      - name: Deploy to GH-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.